name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Android Command Line Tools
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

    - name: Accept specific licenses
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/licenses
        # Android SDK license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        # Preview license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        # Google TV license
        echo "33e4e62e4e44f6730f8cf4d327b0b3f9b445b42d" > $ANDROID_SDK_ROOT/licenses/android-googletv-license
        # ARM DBT license
        echo "859f317696f67ef3d7f507832f877f4a" > $ANDROID_SDK_ROOT/licenses/android-sdk-arm-dbt-license
        # Google GDK license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > $ANDROID_SDK_ROOT/licenses/google-gdk-license
        # MIPS Android license
        echo "e9acab5b5fbb560a72cfaecce8946896ff6aab9d" > $ANDROID_SDK_ROOT/licenses/mips-android-sysimage-license
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses || true

    - name: Install Android SDK components
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: |
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        sdkmanager --uninstall "build-tools;36.0.0-rc1" || true
        sdkmanager --install "build-tools;33.0.2" "platforms;android-33" "platform-tools"

    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip openjdk-11-jdk python3-pip
        pip3 install buildozer cython

    - name: Initialize Buildozer
      run: buildozer init

    - name: Build APK
      run: |
        sudo apt install -y unzip
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
